# Generate key if haven't had yet
# ssh-keygen -t rsa -b 4096 -C "zhangchun88@gmail.com"
# Then add the public key ~/.ssh/id_rsa.pub to the Metadata in GCE
Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "ecocity_public_dashboard"
    google.google_client_email = "acmeideal@gmail.com"
    google.google_json_key_location = "~/ecocity-public-dashboard.json"
    google.name = "ecocity-public-dashboard"

    override.ssh.username = "acmeideal"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
  end

  config.vm.define "webservers" do |webservers|
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "webservers.yml"
    end
  end
end
